### ISSUE TITLE
Suggestion: Set Cursor from Display or Mouse (or both)

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#10]
From what I've seen in most of your code you seem to want to direct people to use your more convenient methods and classes so while it is possible to set the mouse cursor already using `Display.getWindow().setCursor(Cursor);` it might be a good idea to add the ability to set the cursor from the `Display` class or the `Mouse` class directly.

**Comment by sriharshachilakapati** [comment]
Adding a new cursor field for the Display is a good idea, but not from the Mouse. Using mouse will make things complicated if the user wants to set different cursors in different windows if he is using multiple windows.

**Comment by ShadowLordAlpha** [comment]
I suggested Mouse because that was how LWJGL use to do it if i remember correctly

**Comment by sriharshachilakapati** [comment]
Yes LWJGL2 used the Mouse class, but there was only support for one window in LWJGL2. Now that we have multiple windows using LWJGL3, implementing it will not be a good idea.

We should either make the implementation in Mouse class only effect the main Display window, or we should change the cursor on every window. That's the reason I said it's not a good idea, because it won't be clear to the user on what to use.

**Comment by ShadowLordAlpha** [comment]
I wasn't arguing with you but ya it would be confusing if it was in Mouse (Time to go find something else to make a suggestion about :p)
