### ISSUE TITLE
Suggestion: Refactor GameState to State

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#13]
just a suggestion to refactor the class `GameState` to `State` as it is not the Game State but the State the game is in. It also then doesn't take up the name GameState so that can be used instead of PlayState but thats just my own thing.

**Comment by sriharshachilakapati** [comment]
This is just a personal thing, but I'm not going to do this. The reason is, there can be several states in a game, it may be a `GameState` or the `AiState` or the audio `SourceState`, and therefore, naming it just `State` will conflict with others, and may confuse the users.

I'm now close this issue, and if you are very sure that this should be done, please comment explaining why this should be done, and any advantages that this has.
