### ISSUE TITLE
Bug/Limitation/Question: Keyboard not always registering a new Pressed Key

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#14]
Using the `update(delta)` method to call the Keyboard like you do in several of your test classes the method `Keyboard.isClicked(Keyboard.KEY_UP)` along with any other key I have tried does not always register that the key has been pressed. As I recall that system should be running at basically the same speed of the rendering system while update should be running around 60-61UPS so I should be getting a pressed message around once per second at least when spamming the button however it sometimes fails to register that the key has been pressed. This can also be done pressing the key every now and then as the message i have printing to debug this will not print out.

**Comment by sriharshachilakapati** [comment]
I'm interpreting this as a bug, as your description says that it sometimes fails to register the keys. Do you have any test case for this?

The `InputEngine` runs at the same speed as the logic loop, mostly 60 times a second (unless you have changed the `targetUPS`), while the other engines run at a low speed, often limited to 30 times a second due to the VSync.

Maybe, this is what causing the issue, I'm calling the `beginFrame` method of the `InputEngine` twice in a row, and then calling one extra `endFrame` method call in the end. I think this is the issue, will look into it now. It would be helpful if you could make a test case, because I never experienced this myself.

Thanks for reporting.

**Comment by ShadowLordAlpha** [comment]
@Override
	public void update(float delta) {
		// 
		if(Keyboard.isClicked(Keyboard.KEY_UP)) {
			System.out.println("UP");
		}
		
		if(Keyboard.isClicked(Keyboard.KEY_DOWN)) {
			System.out.println("DOWN");
		}
	}

That is the code that is not properly printing out the presses. Its a small test but pressing the key quickly about once every second 25 times only printed 10 of the expected 25 out. Now some of them could have been pressed in the space between the two calls though i would still expect around 20 at least. I could also be holding the key to long however i am just quickly tapping the key like you would when typeing a character on the keyboard. Not pressing it down and holding it.

**Comment by sriharshachilakapati** [comment]
Thanks for sharing the code (I edited that to give it syntax highlighting) and will test it right now.

**Comment by ShadowLordAlpha** [comment]
It could also be something like your time for what is registered as a click is extreamly short though if its shorted than what a normal key press is for something like typeing its basicly useless for any kind of code

**Comment by sriharshachilakapati** [comment]
If you want to read what is typed in, this is not the right way. You have to set a `ICharacterCallback` or a `ICharacterModsCallback` on the window that will give you the characters you typed in the form of unicode code-points.

**Comment by ShadowLordAlpha** [comment]
I was testing different ways to read basic user input but thats good to know. That input didn't seem to register inputs that it should have though I'm entering them with a keyboard and like I said your timeframe for what counts as a clicked is probably very short

**Comment by sriharshachilakapati** [comment]
Clicks are detected per each frame, and it lasts for only one logic frame, that is by default **16.666667** milliseconds. And I also have checked out your demo, this is my code:

```java
private int count = 0;

@Override
public void update(float delta)
{
    if (Keyboard.isClicked(Keyboard.KEY_ESCAPE))
        Game.end();

    if (Keyboard.isClicked(Keyboard.KEY_UP))
        System.out.println(++count);
}
```

With the above code, I did quickly tap it ten times, and the count is 10 times in the output as well. So I guess there is really no bug in the keyboard class.

**Comment by ShadowLordAlpha** [comment]
odd but ok. You should probably make click time based and not frame based so its consistant even when the engine is running at different speeds but again its up to you

**Comment by sriharshachilakapati** [comment]
I don't think it will affect the input at different speeds, because I don't see people who reduce the `targetUPS` value, but only think they increase it. Even if they increase, that shouldn't do any effect, because the `update` is called at the same rate as the input is polled. The user (player) cannot notice the difference.

And, I have did another interesting test, I measured the time taken for me to do a quick tap, taken from an average of 10 sequential taps. And I noticed, I took **~1400 ms** to tap the up arrow key as fast as I could. That means, **140 ms** for a single tap which is very large when compared to the frame time of **16.666667 ms** for a single frame.

Now, if we increase the `targetUps`, the frame time will only decrease, so there is no issue. And now in the case of decreasing it, I never saw anybody using a logic rate of less than 30, because otherwise, the motion will appear sharp and not smooth. And calculating for 30, the frame rate will be **33.333334 ms** which is still less than the 140 millis, so there is no need to worry about this.

```java
private int count = 0;
private double startTime = -1;

@Override
public void update(float delta)
{
    if (Keyboard.isClicked(Keyboard.KEY_ESCAPE))
        Game.end();

    if (Keyboard.isClicked(Keyboard.KEY_UP))
    {
        if (startTime < 1)
            startTime = TimeUtils.currentMillis();

        System.out.println(++count);

        if (count >= 10)
        {
            double endTime = TimeUtils.currentMillis();
            System.out.println("It took you " + (endTime - startTime) + " millis to press 10 ticks");

            startTime = TimeUtils.currentMillis();
            count = 0;
        }
    }
}
```

This is the code that I have used to test my speeds. I'd like to see what you can produce with this, but I guess there is really no need to change anything in the input engine, and also in the Keyboard class, so I'm now closing this issue. You can still comment once it is closed.
