### ISSUE TITLE
Suggestion: Remove lwjgl-natives.jar

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#34]
LWJGL will load up the native it needs now instead of the proper one needing to be loaded by the user so its possible to get rid of the packed version that Silence uses and just replace it with the normal LWJGL natives folder though to keep everything clean it should probably also be placed in its own folder with the jar within the libs folder.

**Comment by sriharshachilakapati** [comment]
This will not be done, because of two reasons. One, the LWJGL natives must match the LWJGL jar, and using other natives (a version mismatch) causes a runtime exception. Second, that will defeat the purpose of our `NativesLoader` and increases the complexity of setting up in the users end. I think adding a JAR to the build path is more easy than setting the native library location of the project.

If you still want to specify the natives in the directory, you can disable the natives loader using properties, and do it just the manual way you'd do in pure LWJGL applications:

```java
public static void main(String[] args)
{
    System.setProperty("NativesLoader", "false");
    new MyGame().start();
}
```

Keep in mind, that if you did the above, you have to set the `java.library.path` property with the location of the natives directory.
