### ISSUE TITLE
Copies of the same basic exception

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#35]
Is there any real reason that we have 3 copies of several different exceptions just with a different parent class? for example the `OutOfMemoryException` where you can set all the base exceptions to `SilenceException` and then just set the message to be different depending on whats throwing the exception

**Comment by sriharshachilakapati** [comment]
The reason is I want to keep the audio and graphics modules separate. One `OutOfMemoryException` arises from OpenAL calls, and hence it's the child of `ALException` class. Another exception with the same name arises from OpenGL calls, and hence it's the child of `GLException` class. This way, the stacktrace will also be clean, as we see either `ALException$OutOfMemoryException` or `GLException$OutOfMemoryException`. I won't be fixing this, as fixing this adds no real advantages.
