### ISSUE TITLE
A Circle is not an Ellipsis (strictly speaking)

### ISSUE THREAD

**Issue by httpdigest** [sriharshachilakapati/SilenceEngine#47]
Hi Sri,

just wanted to tell you about the "Liskov substitution principle". It's not a severe issue with two classes in SilenceEngine, just one thing you might want to be aware of. You can ignore it. :)

I just had a very interesting read on the ["Liskov substitution principle"](https://en.wikipedia.org/wiki/Liskov_substitution_principle). A very good video by the famous Robert C. Martin is here: https://www.youtube.com/watch?v=QHnLmvDxGTY&t=1h13m50s

Applied to your Circle and Ellipsis classes, it says that an `Ellipsis` should not be used instead of a `Circle` (and therefore Circle should not be a subclass of Ellipsis) because it would possibly violate the assumption of a user that statically an Ellipsis always has two radii, that may be different.
So upon seeing a Circle (object with runtime-type Circle), it is possible to still set it to two different radii when using the Ellipsis interface.

Examples of this would be a "draw" method which, upon seeing an Ellipsis, drew an ellipsis with two different radi.
In order to draw a circle now, we would then need to have type-specific switch-cases for the Circle derivative of Ellipsis in order to handle the case of a circle actually being an ellipsis with two equal radii, hence only taking the radiusX into account. This would couple a client to all of the derivatives of Ellipsis and would increase rigidity of the code.
Also, it is possible for a Circle to have two different radii (through its Ellipsis interface) and therefore any draw method must know whether the runtime type is actually an Ellipsis or a Circle.

Again, this is just one thing that came to my mind right now when somewhere in the past I was going over SilenceEngine's code, and it might not be a problem depending on the assumptions made by clients using it.

EDIT: this problem is actually known and given a name: https://en.m.wikipedia.org/wiki/Circle-ellipse_problem

**Comment by sriharshachilakapati** [comment]
Since my childhood, I have heard my geometry teacher say that a circle is an ellipse whose radii of major axis and minor axis are equal, so there is just one radius of course. So a circle is indeed an ellipse and I think the substitution principle doesn't take much work here.

Of course, thanks for those links, I learned a new principle today. And you pointed me to a bug too, when a user uses the `setRadiusX` (or the y equivalent) method of the Ellipse class on a Circle object, the circle will be turned into an ellipse, though it is an instance of circle. Will fix this any time soon.

And regarding drawing, these shapes are not for drawing, these are intended to be used as collision shapes, but the `Graphics2D` class contains methods which has separate methods that renders the Ellipse (denoted there as oval) and circle shapes.

**Comment by httpdigest** [comment]
Hehe. yes, funny, isn't it? It really makes one think about what the "is a" relationship really means. The thing with "a circle is an ellipsis" or "a square is a rectangle" is that it makes a statement about the properties of the object and the relation between the properties values. These conditions however can't be modeled with inheritance in an OO language like java. That's what the liscov substitution principle is about.

**Comment by ShadowLordAlpha** [comment]
Well in math a lot of things go from complex to simple with special shortcuts you can use in the simple ones. The complex equation works for both but the simple only works for one and that's why its a "is a" thing. Its easier to program it backwards because it then becomes simple to complex but that confuses people.

For the circle thing you could just override the methods and have them both set r though I didn't look at the class so Idk if that would cause problems.

Another way would be to just get rid of the circle class and make everyone use an oval or whatever and add a method to set both radius values

**Comment by httpdigest** [comment]
The simple solution in this case and in all other cases that vilate the LSP is simply to break the inheritance relation by not making Circle inherit from Ellipsis, but make those two classes siblings,because inheritance does not represent the "is a" relation.
To illustrate let me propose another instance of the exact same problem by stating the following: "Every point is alway a line segment."
Now if we think about the properties of a line segment, it is that it can be defined by two point.
Now, the special case that makes a line segment be a point is just that both line segment endpoints are identical. ;)
It's exactly equivalent to the ellipsis/circle and rectangle/square problem.
However, no one would model a class Point to inherit from class LineSegment. How come? ;)

**Comment by ShadowLordAlpha** [comment]
True but most people learn that differently as in there is a point, 2 points that are not the same connected makes a line segment from that extend one side to infinity you get a ray extend both you get a line.

With shapes they learn (at least where I was) you have a rectangle if all 4 sides are the same length and connected its a square. All rectangle formulas work for squares but not all square formulas work for rectangles.

Also shrink any shape with a position to 0 and you get a point as a point is just a position not a shape.

**Comment by httpdigest** [comment]
Yes. I totally agree with you. :)
That is fun. Actually, I have given it more thought (not just for fun, but because I need it for my work right now) and I guess it all boils down to this: Mutability of an object's state.
If a Circle were immutable, it would make perfect sense to inherit from Ellipsis, as then we can have a single fixed radius and use that as the two radii for Elipsis.
However, if the class is mutable, and therefore both radii can change during runtime, you always have either one of the following two problems:
1. you decide to enforce the condition that both radii are always equal by implementing that in the setter methods (or generally any method that potentially changes one or the other radius). This would however break a client, as the client, once it statically sees an Ellipsis, would not assume one radius to change when it modifies the other
2. you decide not to enforce that condition of both radii always being identical, in which case you would not break a client, but would allow circumstances in which a Circle is no true circle anymore, when the two radii are assigned different values

However you decide: If you have inheritance, you are always going to have either problem 1 or problem 2.

And the general statement can be made like this:
Whenever you have two classes of objects (and I'm not talking about Java "class" classes, I'm just talking about a set of "equval" things), where there is a subclass relationship between them and that subclass is defined by a restriction/condition on the possible values of the superclasse's properties (inner and outer radius in the ellipsis/circle example), and the state of an object of that class is mutable, then one should not use inheritance as that would cause either of the aforementioned problems.

I fully agree with everything you said above! :) Don't take me wrong. Just wanted to explain why inheritance is the wrong way to model this.

**Comment by httpdigest** [comment]
Oh, another neat example just came to my mind about mutability and subclass being a subclass because of restrictions on the possible property values:

Consider this: You have a class Square that has a property "color". Now you declare a subclass "RedSquare" inheriting from Square. And a Square is a RedSquare iff its color is "red". :)
So, here again one used inheritance to model a subclass relationship that is defined by the restriction on the constellation of the superclasse's properties, which can change.

So, one can either choose:
1. Restrict the color of a RedSquare to always be "red", no matter what a client uses in "setColor()", or
2. allow a client to freely set the color, in which case the subclass relationship breaks

I think that drives home the point quite easily. :)

**Comment by ShadowLordAlpha** [comment]
I agree its the wrong way but in peoples mind its the way it should be because of the math relation and the best way to use inheritance would be to make them go backwards so from square to rectangle because rectangle can use all of squares values but not the other way around without the problems you mentioned, in my opinion. That would not follow math rules though and confuse most people as the order it should be is reverse 

Not really arguing with you just trying to think along different lines. If it was a real problem I would probably remove the square and circle classes and just add methods in the ellipse and rectangle classes.

**Comment by ShadowLordAlpha** [comment]
Ya it does as flipping the order there makes even less cense than with the square or circle normally.

**Comment by ShadowLordAlpha** [comment]
Oh something that came to my mind was to make a single class called something like ColoredSquare and all it provides is a color and a square the subclasses would have to implement the classes to set the values so red square could provide access to the square but not setting the color and a colorable square provides access to both but then the code just keeps getting more and more complicated and in that instance a component based architecture might be better than inheritance

**Comment by httpdigest** [comment]
Thinking out loud is really nice at times. Just everyone saying what they think. :)
I just thought how in the like 6 years of me being an IT consultant and getting to know some customers with their frameworks and applications and all that, that I've never seen inherintance to be used to model objects of the real world using "is a" relations. Inheritance was never used for this. It was only user to have polymorphism to be able to implement crosscutting concerns like logging and profiling and authntication anf authorization and such.
I've just never seen cases of a true inheritance tree to model "is a" relations. Maybe because of the implications that LSP has.
Again, just thinking loud. :)

**Comment by ShadowLordAlpha** [comment]
Its normally used to reduce code duplication or in games Weapon is a Item or something along those lines. Components can also be used though in general they are a bit more complicated to use. I don't really know what programs you look at but what you said seems right as well. you could also use it in JOML to connect all the vector (4f is a 3f is a 2f) classes together so that a something like this would work

`new Vector2f(0,0).add(new Vector3f(1,6));`

With the add method only being `public Vector2f add(Vector2f v) ...` but the 3 and 4 vectors would have to define up for Vector2/vector3 if that was wanted as well. This is because vector3 is a vector2 just with a z value added. 

I think I started rambling but Meh

**Comment by sriharshachilakapati** [comment]
Of course inheriting that way will reduce code duplication, but I'm now thinking just having the same 5 lines in two classes with minor changes cannot be considered as duplicated code, Ellipse has both rx and ry in the equation and in Circle, I've substituted them both with a single radius value.

**Comment by httpdigest** [comment]
erm.. a Circle is also not a polygon, iff your polygon is mutable, for the same reasons explained above. :)
Also you would never treat a circle to be a polygon in collision detection and what not, since it will be wildly inefficient to represent the circle using many corner points (i.e. polygon). You would want to represent the circle as simply a center position and a radius. Inheriting circle from anything else will make your code hard to maintain, as explained because you would need instanceof all over the place.

**Comment by sriharshachilakapati** [comment]
@httpdigest I took a lot of time to think about this, I think we can make everything a polygon and take away the inheritance here. We should be able to add `circle.toPolygon()` and other methods to the shapes. This will be a good idea so in the end, every shape is a polygon so it doesn't create issues now. What do you think of this?

**Comment by sriharshachilakapati** [comment]
@httpdigest

This is now only partly fixed, the same affects the 3D geometry classes too. Can you say if this is a good idea, or is there any other more better idea?

Now the Rectangle, Circle and Ellipse are standalone classes, and each has a createPolygon method. Collision detection is now done with the polygons.
