### ISSUE TITLE
Billboarded sprites (w/ BillBoardModel) don't seem to support transparent PNGs.

### ISSUE THREAD

**Issue by Jeviny** [sriharshachilakapati/SilenceEngine#48]
Here's a screenshot:
![https://i.imgur.com/2MD3thv.png](https://i.imgur.com/2MD3thv.png)
Here's the image I'm using:
![https://i.imgur.com/emjG8KI.png](https://i.imgur.com/emjG8KI.png)
  
Thanks!

**Comment by sriharshachilakapati** [comment]
Got this issue fixed by letting ModelBatch render these BillBoardModels after all the other objects are rendered, and also sorting the BillBoardModels based on the distance from origin.

![BillBoardModelTest](http://i.imgur.com/dxswgEj.png)

This however still causes an issue when two sprites are having same distance, that will cause the billboards to intersect and cause depth fighting. Make sure that they are rotated towards the camera to prevent this issue.
