### ISSUE TITLE
A reasonable way to handle files loading

### ISSUE THREAD

**Issue by darkhax** [sriharshachilakapati/SilenceEngine#78]
Currently the file system depends on callbacks to initialize fields. While this solves the issue of threaded downloads on the web platform, I feel it does a significant blow to the quality of the code, and probably has some performance issues as well. Engines with similar coverage get around this issue by creating a separate abstraction layer for files. Each platform then handles it in the appropriate manner, abstracted away from the developer and their code. It should be extremely easy for a similar feature to be added to the SilenceEngine. This would also solve the issues with file loading and saving, which we have discussed in the past. 

Edit: After looking into things further, the exact way this is handled is to have a preloader step which is used by the game/engine to load any assets. This step is independent from the render/update step and must be completed before the game is allowed to move forward. Such an implementation would also solve a few of the race condition issues that the engine seems to have. (loading icons in the wrong order being a past example of such race conditions)

**Comment by sriharshachilakapati** [comment]
This is what I have thought of, and in a way this is solved by using the `ResourceLoader`. Consider a game which has a large sized resources, and it needs one large file in one level. Now in case we are going to keep a preloader, then we have to keep all these files in the memory, which is not the developer of the game wants. This is the reason I went with the callback approach like JavaScript.

And I said that `ResourceLoader` can solve this issue, it is like a pre-loader that you are talking, you tell it which files to preload, and once the loading is done, you can get the files content directly because they are already loaded into the memory.

My question is, why to use the `ResourceLoader` directly in the engine when it is designed to be used by the users?

**Comment by darkhax** [comment]
When loading asset files, the developer would almost always want to keep them in memory. While larger files would be the rare exception. It would make much more sense to preload things by default, and have defined ways of dealing with the exceptions. 

As for your question, I don't really understand what you're asking. Specifically the `used by the users` part.

**Comment by sriharshachilakapati** [comment]
What other engines actually do is they use BrowserFS. I should have searched for it in the beginning, it is awesome and it do really have support for synchronous IO like preloaders do, but once loaded it also caches the data in either LocalStorage, or HTML5 FileSystem or IndexedDB or whatever the browser supports, making it the best choice that we had to have.

I think this can bring us a new synchronous API, even large files means that they need to be loaded only once. This also removes the synchronization issues we have in Android, because we no longer need threads and hence the apps can properly quit without some hacks in `AndroidWindow`.

I'll start by writing GWT bindings to this API.

**Comment by sriharshachilakapati** [comment]
It is time for about a release. This is post-poned for now, but in future version, we will have a synchronous API along with the current asynchronous API.

**Comment by sriharshachilakapati** [comment]
The solution for this is to have the renderers pre created and let the user use the `ResourceLoader` for the purpose of loading the files. This is even more simpler if you use the `ResourceLoadingState`.

To make your files loaded in before the game starts, use the on-init callbacks.

**Comment by sriharshachilakapati** [comment]
Now that the renderers and programs are precreated once in the engine and are cached, I think this is resolved. Regarding access to synchronous IO, that is not possible without increasing memory consumption, and may pose as an issue on HTML5 backend for larger games. So closing this stating that it is now solved.
