### ISSUE TITLE
Forum is not working

### ISSUE THREAD

**Issue by ghost** [sriharshachilakapati/SilenceEngine#91]
silenceengine.goharsha.com/forum returns Bad gateway with the error code 502
![image](https://user-images.githubusercontent.com/106463451/201454633-f7fc8210-24e4-4a80-81c5-4ba0aafa69d4.png)

**Comment by sriharshachilakapati** [comment]
Lately I haven't got much time to invest in here, having turned away from game dev into a full time mobile app developer and hasn't seen much any traffic lately but only spam.

So I took the forum down because I was spending effort to fight spam there with nearly no ROI. I don't intend to start work on this anytime soon unfortunately.

**Comment by ghost** [comment]
Oh, that's sad
